# Numpy Essentials

In [43]:
import numpy as np

## Numpy Arrays

In [44]:
a = np.array([1, 2, 3, 5, 6, 7]) # a one dimensional array or singleton    
type(a) 

numpy.ndarray

In [45]:
print(a.shape)        # technically 6x1, numpy would omit the one.
print (a)

(6,)
[1 2 3 5 6 7]


In [46]:
b = np.array([[1,2,3],[4,5,6]])  # a two dimensional array   
print(b.shape)  
print (b)
  

(2, 3)
[[1 2 3]
 [4 5 6]]


In [47]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[26,27,28]]])
print (c.shape)
print (c)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [26 27 28]]]


### numpy index appetizers

In [48]:
print (a[0], a[1], a[2], a[3] )  
a[0] = 5                 
print (a)                 

1 2 3 5
[5 2 3 5 6 7]


In [49]:
print (b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [50]:
print (c[0,0,0])

1


### numpy datatypes

In [51]:
x = np.array([1, 2])  # numpy chooses the datatype
print (x.dtype)       

int32


In [52]:
x = np.array([1.0, 2.0])  # numpy choose the datatype
print (x.dtype) 

float64


In [53]:

x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
print (x.dtype)          

int64


### special numpy functions for creating arrays

In [54]:
a = np.zeros((4,4))  # need a two dimensional 4x4 array full of zeros
print (a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [55]:
a = np.ones((4,4)) # what if I need ones
print (a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [56]:
a = np.full((4,4), 6)  # If I want to fill my arrays with one number
print (a)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [57]:
a = np.eye(4)  # Identity matrix
print (a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [58]:
a = np.random.random((4,4))  # random numbers. we eventually deal with probability functions with scipy.stats
print (a)

[[0.60456462 0.7331232  0.54127915 0.08414324]
 [0.30509267 0.8534586  0.69315709 0.27819614]
 [0.72812145 0.65486559 0.62500576 0.29219586]
 [0.3639448  0.23543033 0.02191525 0.56637766]]


In [59]:
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [60]:
a = np.magic(3) # my favourite from matlab.

AttributeError: module 'numpy' has no attribute 'magic'

## oops!  sorry not in numpy. So let's try to make ours.

## for what?????

## 1. If you want to have an idea of the magic called numpy.
## 2. Magic squares are kind of cool. sum all the rows in a column and all the columns in a row, you get the same result.

## Algorithm

Step 1. Start in the middle of the top row, and let n=1;

Step 2. Insert n into the current grid position;

Step 3. If n=NxN  the grid is complete so stop. Otherwise increment n;

Step 4. Move diagonally up and right, wrapping to the first column or last row if the move leads outside the grid. If this cell is already filled, move vertically down one space instead;

Step 5. Return to step 2.

In [ ]:
# NxN magic square.  Extra credit stuff
import numpy as np

N  = 3
magic_square = np.zeros((N,N), dtype=int)

n = 1
i, j = 0, N//2  # check below if the // is weird

while n <= N**2:  # while n is less than NxN
    magic_square[i, j] = n
    n += 1
    newi, newj = (i-1) % N, (j+1)% N # some modular arithmetic so that we never go out of bounds
    if magic_square[newi, newj]:
        i += 1
    else:
        i, j = newi, newj

print(magic_square)


# In Python 3.0, 5 / 2 will return 2.5 and 5 // 2 will return 2. 
# The former is floating point division, and the latter is floor division, sometimes also called integer division.
# In Python 2.2 or later in the 2.x line, there is no difference
# reference http://stackoverflow.com/questions/183853/in-python-2-what-is-the-difference-between-and-when-used-for-division

### reference
1. [creatting a magic square](http://scipython.com/book/chapter-6-numpy/examples/creating-a-magic-square/)
2. [why // instead of /](http://stackoverflow.com/questions/183853/in-python-2-what-is-the-difference-between-and-when-used-for-division) 

## Numpy Array Indexing

In [ ]:
print (b)

In [ ]:
print (b[:1,:2])  # slice indexing

In [ ]:
print ("sliced b:{}".format(b[:1,:2]))  # if you want to print like a pro

In [ ]:
# use slicing to get all the second rows
print (b[1,:])

In [ ]:
# or all the secondcolumn
print b[:,1]

In [ ]:
# or get second and third rows
print (b[:,1:])

In [ ]:
# be careful with the indexing, it starts from the first number and ends in (second nuber -1)

In [ ]:
print (b)

In [ ]:
print (np.array([b[0,0],b[1,0], b[1,2]])) # same as below  # integer indexing

In [ ]:
print (b[[0,1,1],[0,0,2]])  # same as above  # integer indexing

In [ ]:
# you can perform operations on this subset of the whole array.
b[[0,1,1],[0,0,2]] += 10
print (b)

In [ ]:
print (b > 10)  # boolean indexing

In [ ]:
print (b[b>10])

## Numpy array Math operations

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])

In [ ]:
print (x+y)
print (np.add(x,y))

In [ ]:
print (x-y)
print (np.add(x,y))

In [ ]:
print (x*y)
print (np.multiply(x,y))

In [ ]:
print (x/y)
print (np.divide(x,y))

In [ ]:
print (np.sqrt(x))

In [ ]:
v = np.array([2,1,2])

In [ ]:
print (x.shape)
print (v.shape)

In [ ]:
# matrix multiplication is possible for x and v  or  for y and v.  # note the order
print (x.dot(v))

In [ ]:
print (np.dot(x,v))

In [ ]:
# what if we try to change the order, disobeying matrix multiplication rule.
print (np.dot(v,x))

### oops !  numpy doesn't allow that.

In [ ]:
print (x)
print np.sum(x) # sums all the elements of x

In [ ]:
print (np.sum(x, axis=0)) # sums all the the columns.

In [ ]:
print (np.sum(x, axis=1)) # sums all the rows.

In [ ]:
print (x.T)

In [ ]:
print (x.flatten())

## Array Broadcasting

### useful for performing a repeated operation on a large numpy array by a small one. 

Consider a scenario where we would like to subtract a small array from all the rows of a bigger one.

In [ ]:
# first approach 
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 1, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# subtract vector v from each row of matrix x with a for loop
for i in range(x.shape[1]):
    y[i, :] = x[i, :] - v
    
print (y)    

# with a very large x, the loop could be very slow

In [ ]:
# second approach
# we would pile the v's on top each other
vv = np.tile(v, (3, 1))
y = x - vv
print (y)

In [ ]:
# third approach. numpy broadcasting allows us to do this without piling arrays
y = (x-v)
print (y)

## END For Now

## REFERENCES

1. [Stanford Numpy tutorials](http://cs231n.github.io/python-numpy-tutorial/)
2. [Numpy reference](https://docs.scipy.org/doc/numpy/reference/)